"use client";

import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { ArrowRight, ExternalLink, FastForward, Play, Search, Sparkles, Ticket, UserRound } from "lucide-react";

type Stop = { year: string; kind: string; title: string; bridge: string; source: string; url: string; embed?: string };
const stops: Stop[] = [
  { year: "1988", kind: "Music video", title: "Pure Energy / Information Society", bridge: "A transmission about minds and machines opens the signal.", source: "Official artist video · YouTube", url: "https://www.youtube.com/results?search_query=Information+Society+What%27s+On+Your+Mind+official" },
  { year: "1987", kind: "Game guide", title: "How to Win at Super Mario Bros.", bridge: "The signal becomes a map: pipes, shortcuts and hidden routes turn a song about thought into a world you can navigate.", source: "Internet Archive", url: "https://archive.org/details/How_to_Win_at_Super_Mario_Bros_NES_1987", embed: "https://archive.org/embed/How_to_Win_at_Super_Mario_Bros_NES_1987" },
  { year: "1959", kind: "Song & animation", title: "Once Upon a Dream", bridge: "Mario's rescued princess leads backward to an earlier pop-culture princess and the idea that a remembered dream can guide a journey.", source: "Official Disney search · YouTube", url: "https://www.youtube.com/results?search_query=Disney+Once+Upon+a+Dream+official" },
  { year: "1927", kind: "Film", title: "Metropolis", bridge: "The dream becomes a city of machines—an early cinematic future now viewed from our present.", source: "Internet Archive search", url: "https://archive.org/search?query=title%3Ametropolis+AND+year%3A1927" },
  { year: "1980–2000", kind: "Commercial art", title: "Video-game adverts from comics", bridge: "Metropolis sold a mechanical future; these ads show how later artists sold playable futures to a new generation.", source: "Internet Archive", url: "https://archive.org/details/comic-videogame-adverts", embed: "https://archive.org/embed/comic-videogame-adverts" },
];
const tours = [
  { title: "Signals, Pipes & Princesses", guide: "Time Surfers AI", years: "1927–2000", tags: ["music", "games", "film"] },
  { title: "Arcades After Midnight", guide: "Maya R.", years: "1978–1996", tags: ["games", "commercials"] },
  { title: "The Web We Lost", guide: "Theo K.", years: "1994–2009", tags: ["websites", "design"] },
];

export default function Home() {
  const [active, setActive] = useState(0);
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => tours.filter(t => `${t.title} ${t.guide} ${t.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const stop = stops[active];
  return <main className="min-h-screen">
    <header className="topbar"><a className="brand" href="#home"><span className="brandmark">TS</span><span>TIME<br/>SURFERS</span></a><nav><a href="#tour">Tour</a><a href="#discover">Search</a><a href="#guide">Guide profile</a><a href="#apply">Apply</a></nav><Button className="wallet"><Ticket size={16}/> Infinity wallet</Button></header>
    <section id="home" className="hero"><div className="eyebrow"><Sparkles size={15}/> AI-CURATED TRAVEL THROUGH RECORDED TIME</div><h1>The past is<br/><em>still playing.</em></h1><p>Follow human-guided, AI-finished tours through movies, music, games, paintings, commercials and vanished websites—each stop chosen because it belongs after the last.</p><div className="heroActions"><Button asChild size="lg"><a href="#tour"><Play size={17}/> Start the first tour</a></Button><Button asChild size="lg" variant="outline"><a href="#apply">Become a guide <ArrowRight size={17}/></a></Button></div><div className="timeRail"><span>PAST</span><div/><b>YOU ARE HERE</b></div></section>
    <section id="tour" className="tourSection"><div className="sectionHead"><div><span className="kicker">FIRST DIGITAL TOUR · 01</span><h2>Signals, Pipes<br/>& Princesses</h2></div><p>A sample editorial journey connecting synthetic pop, hidden game worlds, a princess song, machine-age cinema and the art that sold video games.</p></div><div className="playerGrid"><div className="screen">{stop.embed ? <iframe title={stop.title} src={stop.embed} allowFullScreen/> : <div className="screenFallback"><span>{stop.year}</span><h3>{stop.title}</h3><p>{stop.source}</p><Button asChild><a href={stop.url} target="_blank" rel="noreferrer">Open official source <ExternalLink size={15}/></a></Button></div>}<div className="screenLabel"><Badge>{stop.kind}</Badge><span>STOP {active + 1} / {stops.length}</span></div></div><aside className="nowPlaying"><span className="kicker">NOW SURFING · {stop.year}</span><h3>{stop.title}</h3><p>{stop.bridge}</p><a href={stop.url} target="_blank" rel="noreferrer">View source details <ExternalLink size={14}/></a><Progress value={((active + 1) / stops.length) * 100}/><div className="controls"><Button variant="outline" disabled={active===0} onClick={()=>setActive(v=>Math.max(0,v-1))}>Back</Button><Button onClick={()=>setActive(v=>(v+1)%stops.length)}><FastForward size={16}/> Skip forward</Button></div><div className="adSlot"><span>SPONSOR BREAK</span><b>Your brand between compatible tour stops</b><small>Clearly labeled · guide revenue share · no interruption mid-work</small></div></aside></div><div className="stopStrip">{stops.map((s,i)=><button key={s.title} className={i===active?"active":""} onClick={()=>setActive(i)}><span>{String(i+1).padStart(2,"0")} · {s.year}</span><b>{s.title}</b></button>)}</div></section>
    <section id="discover" className="discover"><div className="sectionHead"><div><span className="kicker">TOUR INDEX</span><h2>Find a route<br/>through history.</h2></div><div className="searchBox"><Search size={19}/><Input aria-label="Search tours" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search era, medium, guide or idea"/></div></div><div className="tourCards">{filtered.map((t,i)=><article key={t.title}><div className="cardNumber">0{i+1}</div><span>{t.years}</span><h3>{t.title}</h3><p>Guided by {t.guide}</p><div>{t.tags.map(x=><Badge key={x} variant="outline">{x}</Badge>)}</div><Button variant="ghost">View tour <ArrowRight size={15}/></Button></article>)}</div>{!filtered.length && <p className="empty">No tour matches yet. Try “music,” “websites,” or a guide name.</p>}</section>
    <section id="guide" className="profile"><Avatar className="profileAvatar"><AvatarFallback>TS</AvatarFallback></Avatar><div><span className="kicker">FOUNDING GUIDE PROFILE</span><h2>Time Surfers AI</h2><p>The first house guide demonstrates the format: a human supplies the spark and source list; AI checks the links, clarifies the theme, writes transitions and assembles a skippable sequence.</p><div className="stats"><span><b>1</b> published tour</span><span><b>5</b> verified stops</span><span><b>6</b> media types supported</span></div></div></section>
    <section id="apply" className="apply"><div><span className="kicker">GUIDE APPLICATION</span><h2>Bring the pieces.<br/>AI shapes the route.</h2><p>Submit your tour idea, audience and lawful source links. The review improves the plan, checks availability and rights signals, and returns a production-ready route. Approval is based on safety, source quality and a coherent experience—not status.</p></div><form onSubmit={e=>{e.preventDefault(); alert("Application draft saved in this prototype. Persistent submission is the next production step.")}}><label>Tour name<Input required placeholder="e.g. Neon Saturday Morning"/></label><label>Your connecting idea<Input required placeholder="What makes every stop belong?"/></label><label>Source links<textarea required placeholder="One YouTube or Internet Archive URL per line"/></label><label>Business plan<textarea required placeholder="Audience, sponsor fit and revenue split"/></label><Button type="submit"><UserRound size={16}/> Review my guide plan</Button><small>Submitting never transfers ownership of your plan or media.</small></form></section>
    <footer><div className="brand"><span className="brandmark">TS</span><span>TIME SURFERS</span></div><p>We travel only through recorded history. Sources remain with their owners; tours add context, sequencing and discovery.</p><span>Infinity ® · 2026</span></footer>
  </main>;
}
